(function(g){var window=this;'use strict';var Qmb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Rmb=function(a,b){var c=new g.XS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Smb=function(a,b){var c,d,e;
return g.G(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.oE(),2);if(3!=f.j){d=f.B;if(!d)throw g.SD("gct");return g.z(f,g.lT(d),3)}e=f.B;return f.return(e.get("captions",c))})},Tmb=function(a,b,c){Smb(a,b).then(function(d){d&&c(d.trackData,new g.XS(d.metadata))})},Wmb=function(a){if(!Umb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Vmb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Xmb=function(){return g.pD("yt-player-caption-display-settings")},G4=function(){this.segments=[]},Ymb=function(a,b){var c=g.Tb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Hb(a.segments,c),g.Hb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Pb(a.segments,c,0,b),g.Pb(a.segments,c+1,0,b)))},Zmb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.ma=c;this.Z=d;this.G=e;this.W=f;this.D=new G4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.Tu(this.LX,1E3,this);this.events=new g.nL(this);g.M(this,this.N);g.M(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.pA);this.pA();this.LX()},$mb=function(a){return a.j&&a.j.D?a.j.D+a.player.Qc()<a.player.getCurrentTime():!1},anb=function(a,b){var c=g.INa(b,a.policy,{}).gf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ba){d.method="POST";var e=b.D,f=(0,g.n_)([120,0]);e&&g.jP(e,g.$Va);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.AC(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.xOa(h);if(m){h=g.INa(a.B,a.policy,{});a.B.Nk(h,m);anb(a,a.B);break a}l?a.player.va("capfail",{status:h.status}):(a.player.ri().Li("fcb_r"),m=a.B.fb[0].Pa,null!=a.Z&&a.K!==m&&(l=a.B.fb[0],a.G?a.Z(h.response,1E3*(l.startTime+a.player.Qc())):
a.Z(h.responseText,1E3*(l.startTime+a.player.Qc())),a.K=m))}a.B=null;a.C=null}}).wl(function(h){a.B=null;
a.C=null;var l;a.player.va("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;Ymb(a.D,a.B.fb[0].Pa)},H4=function(a,b){g.cW.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.cK(this.J.U())&&!this.j.isManifestless},cnb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.BWa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Okb.get(e);null==q&&(q=bnb[e]||bnb[e.replace(/-/g,"_")],g.Okb.set(e,q));h=q||h}c.push(new g.XS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
dnb=function(a,b){return null!=b&&b in a.j.j?a.j.j[b]:null},enb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.BWa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},fnb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in g.blb?g.blb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={OD:c.OD};c.OD=d;var e=function(f){return function(){return String(a[f.OD])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.OD+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.OD,"gi"),e)}return b},I4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Ue);a.params.Ue&&Object.assign(r,a.params.Ue);Object.assign(r,c.Ue);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Ue=r;var t=1===q.Ki,v=[{I:"span",S:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],x,B,E;(l=l.kb("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(B=x.captions)?void 0:null==(E=B.playerCaptionsTracklistRenderer)?void 0:E.openTranscriptCommand))&&
v.unshift({I:"button",S:"caption-edit",Y:{tabindex:"0","aria-label":fnb()},V:[{I:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.V.call(this,{I:"div",S:"caption-window",Y:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:v});var F=
this;this.K=[];this.Fa=!1;this.B=a;this.Na=this.La=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Mc=c;this.ra=b;this.D=this.Ha("captions-text");this.Zb=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Ua=gnb(d,e,f,h);this.Jc=m;l&&(this.G=this.Ha("caption-edit"),this.T(this.G,"click",function(){F.Jc()}));
this.type=0;this.Za=this.Ua*hnb(r);this.zb=p;a=new g.zV(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.z1,this);a.subscribe("dragmove",this.w1,this);a.subscribe("dragend",this.v1,this);this.ib=this.bb=this.ub=this.qb=0;a="";this.j.windowOpacity&&(a=Wmb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":inb[this.j.textAlign]};this.Zb&&(b["border-radius"]=a?this.Za/8+"px":"");(this.C=
2===this.B.params.Ki||3===this.B.params.Ki)&&jnb(this,this.element);g.ls(this.element,b);if(p){var H;null==(H=this.element.parentElement)||H.style.setProperty("--caption-window-color",a)}switch(this.j.Ol){case 0:case 1:case 2:g.fv(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.fv(this.element,"ytp-caption-window-bottom")}},jnb=function(a,b){var c="vertical-rl";
1===a.j.HR&&(c="vertical-lr");g.gf&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.ls(b,"-o-writing-mode",c);g.ls(b,"-webkit-writing-mode",c);g.ls(b,"writing-mode",c);g.ls(b,"text-orientation","upright");g.fv(b,"ytp-vertical-caption");3===a.B.params.Ki&&(g.ls(b,"text-orientation",""),g.ls(b,"transform","rotate(180deg)"))},hnb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},knb=function(a,b){var c={},d=b.background?b.background:a.j.Ue.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Ue.backgroundOpacity;d=Wmb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Zb&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Za/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ua*hnb(b)+"px";d=1;e=b.color||a.j.Ue.color;if(b.color||null!=b.textOpacity)e=Wmb(e),d=null==b.textOpacity?a.j.Ue.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.CM&&(h=e=b.CM);var l=a.Ua/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.KC()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Ue.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.q7&&(c.visibility="hidden");1===b.aX&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.MS||g.RD,3===a.B.params.Ki?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Zn||2===b.Zn||3===b.Zn||4===b.Zn||5===b.Zn)if(g.MS)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Zn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},J4=function(a){a=a.split("px");
return 0<a.length?(a=Number(a[0]))?a:0:0},lnb=function(a){a.N=g.qf("SPAN");
g.ls(a.N,{display:"block"});g.fv(a.N,"caption-visual-line");a.D.appendChild(a.N)},mnb=function(a,b){var c=g.qf("SPAN");
g.ls(c,{display:"inline-block","white-space":"pre-wrap"});g.ls(c,knb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.ls(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.ls(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},nnb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.Ue);Object.assign(d,c||b.j);Object.assign(d,a.Mc.Ue);(c=!a.N)&&lnb(a);for(var e=a.La&&a.Na&&g.pd(d,a.Na)?a.La:mnb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(lnb(a),e=mnb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.rf(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.MS||!g.ns(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.ns(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Xc?g.ls(e,m,"1em"):g.ls(e,m,"0.5em")))}a.Na=d;a.La=e;a.K.push(b)},gnb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},pnb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new onb(this);this.G=new onb(this);this.j=[];this.clear()},rnb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Iu:a,
Ur:b,result:0};a=qnb[a];b=qnb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ee()&&c.Ur===d;if(d)return{Iu:a,Ur:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Iu:a,Ur:b,result:2};return{Iu:a,Ur:b,result:3}},tnb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,snb(a.D,b,c,d))},unb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.u(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?tnb(a,d.ZU,d.aV,b):1===d.type&&a.B&496&&snb(a.G,d.ZU,d.aV,b);a.j.length=0},K4=function(){this.type=0},L4=function(){this.state=this.Ur=this.Iu=0},vnb=function(){this.timestamp=this.j=0},M4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new K4;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new vnb}},N4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Anb=function(a,b){switch(a){case 0:return wnb[(b&127)-32];
case 1:return xnb[b&15];case 2:return ynb[b&31];case 3:return znb[b&31]}return 0},O4=function(a){return a.B[a.row][a.col]},P4=function(a,b,c){2<=b&&1<a.col&&(--a.col,O4(a).j=0);
var d=O4(a);d.timestamp=a.D.time+0;d.j=Anb(b,c);32>a.col&&a.col++},Bnb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},Q4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Cnb=function(a){a.row=0<a.j?a.j:1;
a.col=1;Q4(a,0,15)},Dnb=function(a){this.C=a;
this.G=0;this.style=new K4;this.K=new M4(this.C);this.N=new M4(this.C);this.text=new M4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Enb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(N4(d,c),Cnb(a.B),Cnb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(N4(d,c),Q4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Fnb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Gnb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},onb=function(a){this.j=a;
this.G=0;this.C=new Dnb(this.j);this.K=new Dnb(this.j);this.B=new L4;this.D=this.C},snb=function(a,b,c,d){a.B.update();
b=rnb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Iu;c=b.Ur;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&P4(a,0,b),c&96&&P4(a,0,c),0!==b&&0!==c&&3===a.style.type&&N4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Iu=e,b.Ur=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Bnb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));Q4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:P4(b.j,0,32);break a;case 48:57===c?(d=b.j,O4(d).j=0,32>d.col&&d.col++):P4(b.j,1,c&15)}break;case 2:c&32&&P4(b.j,2,c&31);break;case 3:c&32&&P4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Fnb(b);
break;case 33:d=b.j;1<d.col&&(--d.col,O4(d).j=0);break;case 36:d=b.j;b=O4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Enb(b,2,d);break;case 38:Enb(b,3,d);break;case 39:Enb(b,4,d);break;case 40:P4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Cnb(d);Gnb(b);break;case 43:Gnb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:N4(a,
d)}Q4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;N4(a,d);Bnb(a,b,b+1,a.j-1);Q4(a,a.row,1)}break;case 46:Q4(b.D,0,15);break;case 47:N4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Fnb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},Hnb=function(){},R4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.AK.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Jnb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Zf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Inb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new R4(a,b,e,c,l,d,m)}switch(m.Zf){case 9:case 10:m.Zn=1;break;case 11:m.Zn=2;break;case 12:m.Zn=3;break;case 13:m.Zn=4;break;case 14:m.Zn=5}return new R4(a,b,e,c,l.textContent||"",d,m)},Inb=function(a,b,c,d,e){var f=g.KC(),h=
f?g.qf("DIV"):g.qf("RUBY"),l=g.qf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.qf("DIV"):g.qf("RP");a.textContent=b;h.appendChild(a);b=f?g.qf("DIV"):g.qf("RT");b.textContent=c;h.appendChild(b);c=e.Zf;if(10===c||11===c||12===c||13===c||14===c)if(g.ls(b,"text-emphasis-style","filled circle"),g.ls(b,"text-emphasis-color","currentcolor"),g.ls(b,"webkit-text-emphasis","filled circle"),11===e.Zf||13===e.Zf)g.ls(b,"webkit-text-emphasis-position","under left"),g.ls(b,"text-emphasis-position","under left");c=!0;if(4===e.Zf||7===e.Zf||12===e.Zf||
14===e.Zf)g.ls(h,"ruby-position","over"),g.ls(h,"-webkit-ruby-position","before");else if(5===e.Zf||6===e.Zf||11===e.Zf||13===e.Zf)g.ls(h,"ruby-position","under"),g.ls(h,"-webkit-ruby-position","after"),c=!1;e=f?g.qf("DIV"):g.qf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.ls(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.ls(f,"display","none"),f=f.nextElementSibling,g.ls(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.ls(h.lastElementChild,"display","none"),d?(g.ls(h,"padding-top","0.6em"),g.ls(f,"top","0")):(g.ls(h,"padding-bottom","0.6em"),g.ls(f,"bottom","0")));return h},S4=function(){g.I.apply(this,arguments)},T4=function(a,b,c,d,e){g.AK.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Knb=function(a){var b="_"+U4++;
return new T4(0,0x8000000000000,0,b,a)},V4=function(a){S4.call(this);
this.D=a;this.pens={};this.Z={};this.W={};this.G="_"+U4++;this.N={};this.C=this.j=null;this.K=!0},W4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},X4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},Y4=function(a,b){a=W4(a,b);
return void 0!==a?a:null},$4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Z4.test(a),a},Lnb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.W[d]:a.D);a=Y4(b,"mh");null!=a&&(c.Xz=a);a=Y4(b,"ju");null!=a&&(c.textAlign=a);a=Y4(b,"pd");null!=a&&(c.Ki=a);a=Y4(b,"sd");null!=a&&(c.HR=a);a=$4(b,"wfc");null!=a&&(c.windowColor=a);b=W4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Mnb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.Z[d]);a=Y4(b,"ap");null!=a&&(c.Ol=a);a=W4(b,"cc");null!=a&&(c.Yr=a);a=W4(b,"ah");null!=a&&(c.Zj=a);a=W4(b,"rc");null!=a&&(c.qr=a);b=W4(b,"av");null!=b&&(c.ao=b);return c},Nnb=function(a,b,c,d){var e={};
Object.assign(e,Mnb(a,b));Object.assign(e,Lnb(a,b));d?g.pd(e,a.D)?(d=a.G,e=a.D):d="_"+U4++:d=b.getAttribute("id")||"_"+U4++;a=W4(b,"t")+c;b=W4(b,"d")||0x8000000000000;if(2===e.Ki||3===e.Ki)c=e.qr,e.qr=e.Yr,e.Yr=c;return new T4(a,b,0,d,e)},a5=function(a){S4.call(this);
this.K=a;this.j=new Map;this.D=new Map;this.G=new Map;this.C=new Map},b5=function(a){a=g.we(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Onb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.G.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.qr=a);b=b.ccColCount;void 0!==b&&(f.Yr=b);if(2===f.Ki||3===f.Ki)b=f.qr,f.qr=f.Yr,f.Yr=b;return new T4(c,d,0,e,f)},c5=function(a,b,c,d){g.cW.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.D=b.hx},d5=function(a,b,c,d,e,f,h,l,m,n){I4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},e5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},f5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},g5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},h5=function(a,b){S4.call(this);
this.C=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.j=new pnb;this.j.B=1<<this.track},Qnb=function(a){if("string"===typeof a)return!1;
a=new e5(a,8,0);return Pnb(a)},Pnb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==g5(a))return!1;
a.version=f5(a);if(1<a.version)return!1;f5(a);f5(a);f5(a);return!0},i5=function(a,b,c,d,e,f,h,l,m,n){I4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ba=[];this.ma=this.W=this.Ta=0;this.Ea=NaN;this.Rb=0;this.ac=null;this.Xa=new g.Tu(this.p$,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.zV(this.element,!0),g.M(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.fv(this.element,"ytp-caption-window-rollup");g.M(this,this.Xa);g.ls(this.element,"overflow","hidden")},Rnb=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.HR&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Snb=function(a){a.Ba=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.qr,c=0,d=0,e=a.Ba.length-1;c<b&&-1<e;){var f=a.Ba[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.W=d;b=Math;c=b.max;isNaN(a.Ea)&&((d=a.j.Yr)?(e=g.qf("SPAN"),g.Bf(e,"\u2013".repeat(d)),g.ls(e,knb(a,a.j.Ue)),a.D.appendChild(e),a.Ea=e.offsetWidth,a.D.removeChild(e)):a.Ea=0);d=a.D;a.ma=c.call(b,a.Ea,a.Rb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Tnb=function(a,b){Snb(a);
var c=a.Ba.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.W-c;if(c!==a.Ta){var d=0<c&&0===a.Ta,e=c<a.Ta;b||isNaN(c)||d||!e||(g.fv(a.element,"ytp-rollup-mode"),g.Uu(a.Xa));g.ls(a.D,"transform",Rnb(a,c));a.Ta=c}Snb(a)},j5=function(){S4.call(this)},Unb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new R4(b,c,d,e.id,p.nodeValue,f||0<n,g.md(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Unb(a,b,c,d,e,!0,p,q,m)}}},Vnb=function(a){var b=a.split(":");
a=0;b=g.u(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Wnb=function(a,b,c,d){d=Object.assign({Xz:0},d);
return new T4(a,b,c,"_"+U4++,d)},k5=function(a,b){g.I.call(this);
this.J=a;this.X=b;this.j=null;this.B=this.J.cz()},bob=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.B&&b){var f=e,h=Xnb(a,b,d),l=[];try{for(var m=g.u(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.BR;l="string"!==typeof q?l.concat(Ynb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(Znb(a,q,r)):l.concat($nb(a,c,q,r))}var t=l}catch(v){g.$F(v),a.clear(),t=[]}if(0!==t.length)return t}b=aob(b);if(!b)return[];try{return"string"!==typeof b?Ynb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Znb(a,b,d):$nb(a,c,b,d)}catch(v){return g.$F(v),a.clear(),[]}},aob=function(a){if("string"===
typeof a||Qnb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.DQ(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.PO(a)},Xnb=function(a,b,c){if("string"===typeof b||Qnb(b))return[{trackData:b,
BR:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.eNa(d);if(a.B&&e){var f=g.WMa(e),h=g.XMa(e);e=e.j;f&&e&&a.B.NF(e,f,h)}a=g.KQ(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.PO(e),f.push({trackData:e,BR:c+1E3*h});cob(d,f,c);return f=f.filter(function(l){return!!l.trackData})},cob=function(a,b,c){var d=g.DQ(a,0,1836476516),e=9E4;
d&&(e=g.EQ(d)||9E4);d=0;for(var f=g.KQ(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.DQ(a,l.dataOffset,1953653094))&&(l=g.DQ(a,l.dataOffset,1952867444))&&(l=g.bNa(l)/e*1E3,0===h&&(d=l),b[h].BR=l-d+c||c*h*1E3)}},Ynb=function(a,b,c,d,e){if(!Qnb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new h5(e,b));return a.j.B(c,d)},Znb=function(a,b,c){a.j||(a.j=new j5);
a=a.j.B(b,c);.01>Math.random()&&g.gG(Error("Deprecated subtitles format in web player: WebVTT"));return a},$nb=function(a,b,c,d){if("{"===c[0])try{return a.j||(a.j=new a5(dob(b))),a.j.B(c,d)}catch(f){return g.$F(f),[]}var e=g.x2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.j||(a.j=new V4(dob(b),a.X)),a.j.B(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},dob=function(a){var b=
{};
if(a=g.$S(a))b.lang=a,g.Xgb.test(a)&&(b.Ki=1);return b},l5=function(a){g.$V.call(this,a);
var b=this;this.J=a;this.X=this.J.U();this.videoData=this.J.getVideoData();this.ub=this.J.rb();var c;this.ib=null==(c=this.J.getVideoData(1))?void 0:g.lU(c);this.C={Ue:{}};this.G={Ue:{}};this.Fa=[];this.ra={};this.Ua={};this.W=!1;this.Zb=g.mU(this.videoData);this.bb=g.CWa(this.videoData,this.J);this.Rb=!!this.videoData.captionTracks.length;this.ac=!!this.videoData.ge;this.Xa="3"===this.X.controlsType;this.j=this.N=this.Z=this.Ta=this.qb=null;this.Za=new k5(this.J,this.X);this.B=null;this.Ba=new g.nL(this);
this.K=new g.V({I:"div",S:"ytp-caption-window-container",Y:{id:"ytp-caption-window-container"}});this.ma={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Rv("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Ev(d));this.storage=c;var e;this.Ib=!(null==(e=a.mf())||!e.EF());this.D=eob(this);this.Ea=!this.D&&this.Xa&&this.Ib&&this.bb;g.M(this,this.Za);this.D?this.Na=this.La=null:(this.La=new g.Ru(this.UR,void 0,this),g.M(this,this.La),this.Na=new g.Tu(this.Yaa,2E3,this),g.M(this,
this.Na));g.M(this,this.Ba);g.NU(this.player,this.K.element,4);g.M(this,this.K);this.D||this.Ba.T(a,"resize",this.WR);(this.zb=g.yS(this.X)&&!g.aD()&&!this.J.isFullscreen()&&!this.D&&!this.Ea)&&this.Ba.T(a,"resize",this.y9);this.Ba.T(a,"onPlaybackAudioChange",this.N8);this.Ba.T(a,g.BK("captions"),function(f){b.onCueRangeEnter(f)});
this.Ba.T(a,g.CK("captions"),function(f){b.onCueRangeExit(f)});
this.ib&&this.Ba.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
fob(this,Xmb()||{});this.player.wc("onCaptionsModuleAvailable")},iob=function(a){if(1===a.X.zb||1===a.videoData.NE||"alwayson"===g.ST(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(2===a.X.zb){if(g.JS(a.X))var c=gob(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Qmb(a.player.getAudioTrack(),g.JS(a.X));var d=g.ST(a.videoData,"yt:cc");if(void 0===hob(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===b||"on"===
g.ST(a.videoData,"yt:cc")},m5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},hob=function(a){var b=void 0,c=g.uD(g.tD(),65);
if(g.JS(a.X)&&null!=c){if(null!=gob(a))return!1;b=!c}return b},job=function(a){var b;
a.Zb?b=new c5(a.X,a.videoData,a.getAudioTrack(),a.player):a.bb?b=new H4(a.videoData.j,a.player):a.Rb?b=new g.dW(a.X,a.videoData,a.getAudioTrack()):b=new g.hW(a.X,a.videoData.ge,a.videoData.videoId,g.PSa(a.videoData),a.videoData.Mm,a.videoData.eventId);return b},o5=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.eU(a.videoData)&&(b=!0);b||(b=a.ac?!1:a.Rb?!1:!0);b=b||kob(a);b=g.aW(a.j.B,b);var c=null;if(g.JS(a.X)){var d=a.J.isInline()?void 0:g.pD("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.ST(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.$S(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.$S(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.u(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.ST(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.$S(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||n5(a));d&&c&&g.$S(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Rmb(d,c));return d}return null},n5=function(a){return a.N&&a.N.j},p5=function(a){var b=n5(a);
return!!b&&a.B===b},lob=function(a){var b=Qmb(a.player.getAudioTrack(),g.JS(a.X)),c;
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=o5(a,a.W):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&m5(a)?c=n5(a):hob(a)||a.W||iob(a)?c=o5(a,a.W):m5(a)&&(c=n5(a));if(a.D||a.Ea){var d=g.aW(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.qf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.YS(f));h.setAttribute("srclang",g.$S(f));h.setAttribute("id",f.toString());a.Ea||h.setAttribute("src",a.j.xv(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.mf();c.nC(b);c=
c.Jb();a.Ib&&a.Ba.T(c.textTracks,"change",a.X$)}else!a.B&&c&&q5(a,c),a.player.wc("onCaptionsTrackListChanged"),a.player.xm("onApiChange")},mob=function(a,b){var c=a.J.mf().Jb().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},q5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.W=c,a.W&&(g.JS(a.X)?r5(a,!!b):s5(a,!!b)));a.B=b;m5(a)&&(a.B=n5(a));var d;nob(a,null!=(d=a.B)?d:void 0);a.load()},pob=function(a,b){if(b instanceof T4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=oob(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Ua[c]||(a.Ua[c]=[]),a.Ua[c].push(b)},oob=function(a,b){var c=qob(a);
if(!c)return null;var d=a.B?g.$S(a.B):null;d&&g.Xgb.test(d)&&(b.params.Ki=1);var e=a.ub.getPlayerSize();d=e.height*a.ma.height;e=e.width*a.ma.width;"google-live"!==a.X.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.Xz?b.params.Xz:1<b.j.length?1:0){case 1:return new d5(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.hL.bind(a),a.J);case 2:return new i5(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.hL.bind(a),a.J);default:return new I4(b,a.C,a.G,c.width,c.height,e,
d,a.X.experiments,a.hL.bind(a),a.J)}},fob=function(a,b,c){c=void 0===c?!1:c;
var d=t5.Ue;a.C={};Object.assign(a.C,t5);a.C.Ue={};Object.assign(a.C.Ue,d);a.G={Ue:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;Z4.test(f);e.Ue.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;Z4.test(f);e.Ue.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||t5.windowColor;Z4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Ue.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Ue.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Ue;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Ue.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=t5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Ue.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Ue.fontFamily=f;a.loaded&&a.WR();c&&g.oD("yt-player-caption-display-settings",b,2592E3)},sob=function(a,b,c){b&&!a.Z?(b=Knb({Ki:0,
lang:"en-GB"}),a.Z=[b,new R4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.sf(a.Z)):!b&&a.Z&&(rob(a,a.Z),a.Z=null)},rob=function(a,b){a.player.Xn(b);
b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.Ib(a.Fa,c.value);g.Su(a.La)},nob=function(a,b){a.X.L("html5_modify_caption_vss_logging")&&(a.videoData.EB=b)},qob=function(a){var b=a.ub.getVideoContentRect(!0).height,c=a.ub.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ma.height;c*=a.ma.width;return{width:c,height:b}},s5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},r5=function(a,b){a.J.isInline()||g.oD("yt-player-sticky-caption",b,2592E3)},gob=function(a){if(!a.J.isInline())return g.pD("yt-player-sticky-caption")},eob=function(a){var b,c=!(null==(b=a.J.mf())||!b.DF());
return a.Xa&&c&&!a.bb},kob=function(a){return a.X.L("web_deprecate_always_includes_asr_setting")&&g.JS(a.X)?!0:!!g.uD(g.tD(),66)};
g.LY.prototype.aD=g.ea(45,function(a){var b=2;this.G.has(a)?b=0:g.Y1a(this,a)&&(b=1);return b});
g.c0.prototype.aD=g.ea(44,function(a){return this.fd.aD(a)});
g.LY.prototype.NF=g.ea(43,function(a,b,c){this.La.set(a,{qs:b,jy:c})});
g.c0.prototype.NF=g.ea(42,function(a,b,c){this.fd.NF(a,b,c)});
g.cW.prototype.xQ=g.ea(41,function(){return!1});
g.cW.prototype.kt=g.ea(40,function(){});
g.dW.prototype.kt=g.ea(39,function(a,b,c){var d=this;this.isDisposed();b=this.xv(a,b);this.Gr();this.j=g.xC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.hW.prototype.kt=g.ea(38,function(a,b,c){var d=this;this.isDisposed();b=this.xv(a,b);this.Gr();this.j=g.xC(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.GV.prototype.By=g.ea(37,function(){for(var a=g.Xe(document,"track",void 0,this.j),b=0;b<a.length;b++)g.vf(a[b])});
g.AY.prototype.By=g.ea(36,function(){this.mediaElement.By()});
g.GV.prototype.EF=g.ea(35,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.AY.prototype.EF=g.ea(34,function(){return this.mediaElement.EF()});
g.GV.prototype.DF=g.ea(33,function(){return!!this.j.textTracks});
g.AY.prototype.DF=g.ea(32,function(){return this.mediaElement.DF()});
g.GV.prototype.nC=g.ea(31,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.AY.prototype.nC=g.ea(30,function(a){this.mediaElement.nC(a)});
g.X_.prototype.pD=g.ea(20,function(){return this.W});
g.g1.prototype.pD=g.ea(19,function(){var a;return(null==(a=g.zU(this))?void 0:a.cz())||null});
g.FU.prototype.cz=g.ea(18,function(){return this.app.pD()});
g.W0.prototype.cz=g.ea(17,function(){var a;return(null==(a=this.Aa)?void 0:a.pD())||null});
g.rQ.prototype.UH=g.ea(3,function(a){return(a=this.cn(a))?a.j:0});
g.pOa.prototype.UH=g.ea(2,function(){return 0});
var Vmb=/#(.)(.)(.)/,Umb=/^#(?:[0-9a-f]{3}){1,2}$/i,bnb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",
dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",
eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",
gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",
ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",
ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",
kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",
na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",
oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",
rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",
sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",
ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",
war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
G4.prototype.contains=function(a){a=g.Tb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
G4.prototype.length=function(){return this.segments.length/2};
g.w(Zmb,g.I);g.k=Zmb.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.pA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Qc();var b=this.j;this.j=g.Bb(this.ma.xq(a).fb);b!==this.j&&this.W&&this.W()};
g.k.reset=function(){this.D=new G4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.LX=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Or(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.RB(a);var b=a.fb[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.cz()){var d=b.j.info.id,e=b.Pa,f=a.fb[0].C;if(this.policy.Ba){if(c=c.WH(f,e,d,3))a.D=c}else if(d=c.Vy(f,e,d,3))if(c=c.aD(e),0===c)d&&(a.j=new g.kQ(d));else if(2===c){this.N.start();$mb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.yn(b.Pa)?(this.D.contains(a.fb[0].Pa)||anb(this,a),this.j=g.Bb(a.fb)):$mb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.w(H4,g.cW);g.k=H4.prototype;g.k.kt=function(a,b,c){var d=this;this.Gr();b=dnb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?enb(this,b,"386"):enb(this,b));if(b){var e=1E3*(b.index.UH(b.index.fn())-b.index.getStartTime(b.index.fn())),f=new g.xWa(this.X),h=function(){d.C&&d.C.reset();d.G=!0};
this.X.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new Zmb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.xL(b.info),h)}};
g.k.xQ=function(){var a=this.G;this.G=!1;return a};
g.k.Lz=function(a){var b=this.K?[new g.XS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.XS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?cnb(this,"386"):cnb(this);b=g.u(b);for(var c=b.next();!c.done;c=b.next())g.bW(this.B,c.value);a()};
g.k.Gr=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.xv=function(){return""};
var Z4=/^#(?:[0-9a-f]{3}){1,2}$/i;var inb=["left","right","center","justify"];g.w(I4,g.V);g.k=I4.prototype;g.k.z1=function(a,b){this.bb=a;this.ib=b;var c=g.vs(this.element,this.element.parentElement);this.qb=a-c.x;this.ub=b-c.y};
g.k.w1=function(a,b){if(a!==this.bb||b!==this.ib){g.ev(this.element,"ytp-dragging")||g.fv(this.element,"ytp-dragging");var c=g.xs(this.element);a=a-this.qb-.02*this.playerWidth;var d=b-this.ub-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.we(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.we(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.we(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.we(c,0,1);this.B.params.Ol=b;this.B.params.ao=c;this.B.params.Zj=
a;this.B.params.isDefault=!1;this.j.Ol=b;this.j.ao=c;this.j.Zj=a;this.j.isDefault=!1;this.ra.Ol=b;this.ra.ao=c;this.ra.Zj=a;this.ra.isDefault=!1;this.NZ()}};
g.k.v1=function(){g.hv(this.element,"ytp-dragging")};
g.k.NZ=function(){this.cB(this.K)};
g.k.getType=function(){return this.type};
g.k.cB=function(a){var b=this.zb?0:Math.min(this.cW(),this.maxWidth),c=this.bW(),d=this.zb;if(d){var e=getComputedStyle(this.D.parentNode);e=J4(e.borderLeftWidth)+J4(e.borderRightWidth)+J4(e.paddingLeft)+J4(e.paddingRight)}else e=0;var f=e;e="";3===this.B.params.Ki&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.ls(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.jM(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=.96*this.j.Zj+2;h=this.j.Ol;switch(h){case 0:case 3:case 6:(d=this.j.Ue.fontSizeIncrement)&&0<d&&2!==this.j.Ki&&3!==this.j.Ki&&(l=Math.max(l/(1+2*d),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=.96*this.j.ao+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.ls(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],"string"===typeof e.text&&(d+=e.text.split("\n").length-1,e.append||0===b||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.jM=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Fa||this.K.length>b)b=0,this.Fa=!1,this.K=[],this.N=this.Na=this.La=null,g.tf(this.D);for(;b<a.length;b++)nnb(this,a[b])};
g.k.cW=function(){return 0};
g.k.bW=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};pnb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
pnb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var qnb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];K4.prototype.set=function(a){this.type=a};
K4.prototype.get=function(){return this.type};
L4.prototype.clear=function(){this.state=0};
L4.prototype.update=function(){this.state=2===this.state?1:0};
L4.prototype.Ee=function(){return 0!==this.state};
L4.prototype.matches=function(a,b){return this.Ee()&&a===this.Iu&&b===this.Ur};
vnb.prototype.reset=function(){this.timestamp=this.j=0};
M4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
M4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
M4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var wnb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],xnb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ynb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],znb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Dnb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
onb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Hnb.prototype.D=function(){};g.w(R4,g.AK);R4.prototype.toString=function(){return g.AK.prototype.toString.call(this)};g.w(S4,g.I);S4.prototype.B=function(){return[]};
S4.prototype.reset=function(){};g.w(T4,g.AK);T4.prototype.toString=function(){return g.AK.prototype.toString.call(this)};
var U4=0;g.w(V4,S4);V4.prototype.reset=function(){this.N={};this.C=this.j=null;this.K=!0};
V4.prototype.B=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.u(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.u(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=X4(a,"b");
null!=l&&(h.bold=l);l=X4(a,"i");null!=l&&(h.italic=l);l=X4(a,"u");null!=l&&(h.underline=l);l=Y4(a,"et");null!=l&&(h.charEdgeStyle=l);l=Y4(a,"of");null!=l&&(h.offset=l);l=$4(a,"bc");null!=l&&(h.background=l);l=$4(a,"ec");null!=l&&(h.CM=l);l=$4(a,"fc");null!=l&&(h.color=l);l=Y4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=W4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=W4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=W4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=Y4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Zf=10<l?l-1:l);a=Y4(a,"hg");null!=a&&(h.aX=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.W[c]=Lnb(this,a);break;case "wp":c=a.getAttribute("id"),this.Z[c]=Mnb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.u(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Nnb(this,a,b,!1);(a=this.N[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.N[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.G;h=!!X4(m,"a");l=(W4(m,"t")||0)+l;var n=W4(m,"d")||5E3;h||(!this.K&&this.C&&this.C.windowId===f&&this.C.end>l&&(this.C.end=l),this.C&&"\n"===this.C.text&&(this.C.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.K=null!=m.getAttribute("d"));for(m=0;m<r.length;m++){var t=r[m],v=void 0;0<m&&(h=!0);var x=void 0;1===t.nodeType&&(x=t);if(x&&"s"===x.tagName){if((t=(t=x.getAttribute("p"))?this.pens[t]:null)&&t.Zf&&(1===t.Zf?(t=r.slice(m,
m+4),4===t.length&&(v=Jnb(l,n,f,h,p,t,this.pens),m+=3)):v=Jnb(l,n,f,h,p,[x],this.pens)),!v){var B=x;v=l;x=n;t=f;var E=h,F=p,H=B.textContent?B.textContent:"",P=B.getAttribute("p");P=P?this.pens[P]:null;B=W4(B,"t")||0;v=new R4(v+B,x-B,F,t,H,E,P)}}else v=new R4(l,n,p,f,t.textContent||"",h,q);c.push(v);this.C=v}if(0<c.length)for(c[0].windowId===this.G&&(this.j=Nnb(this,a,b,!0),d.push(this.j)),a=g.u(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var tob=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.w(a5,S4);a5.prototype.reset=function(){this.C.clear()};
a5.prototype.B=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.u(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.CM=b5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=b5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=b5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Zf=10<h?h-1:h,f.Zn=tob.get(f.Zf));e.hgHorizGroup&&(f.aX=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.u(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.G.get(h)):Object.assign(f,
this.K),void 0!==e.mhModeHint&&(f.Xz=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Ki=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.HR=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=b5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.G.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.u(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.D.get(h)),void 0!==e.ahHorPos&&
(f.Zj=e.ahHorPos),void 0!==e.apPoint&&(f.Ol=e.apPoint),void 0!==e.avVerPos&&(f.ao=e.avVerPos),void 0!==e.ccCols&&(f.Yr=e.ccCols),void 0!==e.rcRows&&(f.qr=e.rcRows),this.D.set(a++,f);if(c.events){a=[];c=g.u(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Onb(this,l,e,f,h),a.push(d),this.C.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+U4++,d=Onb(this,l,e,f,h),a.push(d),this.C.set(h,d));d=a;var m=l;0===f&&(f=5E3);l=this.C.get(h);
var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],v=t.utf8;if(v){var x=t.tOffsetMs||0,B=null;t.pPenId&&(B=this.j.get(t.pPenId));if(2===(null!=l.params.Xz?l.params.Xz:1<l.j.length?1:0)&&n&&"\n"===v)continue;t=null;var E=[],F;if(F=B&&1===B.Zf){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var P=F[H+1].pPenId;(P=this.j.get(P))&&P.Zf&&2===P.Zf?(P=F[H+2].pPenId,P=this.j.get(P),!P||!P.Zf||3>P.Zf?F=!1:
(P=F[H+3].pPenId,F=(P=this.j.get(P))&&P.Zf&&2===P.Zf?!0:!1)):F=!1}}if(F)x=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),v=Inb(v,x,F,t,H),t=new R4(e,f,p,h,v,n,B),m+=3;else{if(-1<v.indexOf("<")){var Q=void 0;E=B;F=r;H=e;P=f;var R=x,ha=p,ua=n,oa=[],ma=g.x2("<html>"+v+"</html>");if(!ma.getElementsByTagName("parsererror").length&&(null==(Q=ma.firstChild)?0:Q.childNodes.length))for(Q=g.u(ma.firstChild.childNodes),ma=Q.next();!ma.done;ma=Q.next()){ma=ma.value;var ra=void 0,ca=void 0,
W=null!=(ca=null==(ra=ma.textContent)?void 0:ra.replace(/\n/g,""))?ca:"";if(3!==ma.nodeType||W&&null==W.match(/^ *$/)){ra={};Object.assign(ra,E||F);ca=void 0;switch(null==(ca=ma)?void 0:ca.tagName){case "b":ra.bold=!0;break;case "i":ra.italic=!0;break;case "u":ra.underline=!0}oa.push(new R4(H+R,P-R,ha,l.id,W,ua,ra))}}E=oa}E.length||(E=[new R4(e+x,f-x,p,l.id,v,n,B||r)])}if(E.length)for(n=g.u(E),B=n.next();!B.done;B=n.next())B=B.value,d.push(B),l.j.push(B);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=
[];return b};g.w(c5,g.cW);c5.prototype.kt=function(a,b,c){Tmb(this.videoData.videoId,a.vssId,c)};
c5.prototype.Lz=function(a){if(this.audioTrack)for(var b=g.u(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.bW(this.B,c.value);a()};g.w(d5,I4);d5.prototype.jM=function(a){var b=this.B.j;I4.prototype.jM.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,uob);var e=c.j;var f=d}nnb(this,c,d)}};
var uob={q7:!0};g.w(e5,Hnb);e5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+U4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new T4(c,d-c,5,f,{textAlign:0,Ol:0,Zj:2.5*b,ao:5.33*a});e=new R4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.w(h5,S4);h5.prototype.B=function(a){a=new e5(a,a.byteLength,this.C);if(Pnb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=g5(a)*(1E3/45):1===a.version&&(a.C=4294967296*g5(a)+g5(a)),a.G=f5(a);0<a.G;a.G--){var b=f5(a),c=f5(a),d=f5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,ZU:c,aV:d,order:b.j.length}))}unb(this.j,a);return a.B}return[]};
h5.prototype.reset=function(){this.j.clear()};g.w(i5,I4);g.k=i5.prototype;g.k.NZ=function(){g.Vu(this.Xa)};
g.k.p$=function(){g.hv(this.element,"ytp-rollup-mode");this.cB(this.ac,!0)};
g.k.bW=function(){return this.C?this.ma:this.W};
g.k.cW=function(){return this.C?this.W:this.ma};
g.k.cB=function(a,b){this.ac=a;if(this.B.params.qr){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Rb=this.ma;this.W=this.ma=0;I4.prototype.cB.call(this,a);Tnb(this,b)}I4.prototype.cB.call(this,a)};g.w(j5,S4);
j5.prototype.B=function(a,b){var c=[];a=a.split(vob);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!wob.test(e)){var h=xob.exec(e);if(h&&4<=h.length){var l=Vnb(h[1]),m=Vnb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.u(n);for(var v=n.next();!v.done;v=n.next())if(v=v.value.split(":"),2===v.length){var x=v[1];switch(v[0]){case "line":v=x.split(",");v[0].endsWith("%")&&(p=v[0],h.ao=Number.parseInt(p,10),2===v.length&&(q=v[1].trim()));break;case "position":v=
x.split(",");r=v[0];h.Zj=Number.parseInt(r,10);2===v.length&&(t=v[1].trim());break;case "align":switch(x){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Zj=0;break;case 1:h.Zj=100;break;case 2:h.Zj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Ol=q}e=e.substring(xob.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Wnb(l,m,5,t),m=new R4(l,m,5,f.id,h,!1,g.md(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(yob),1===q.length?(h=5,t=Wnb(l,m,h,t)):(p=h=6,t=Object.assign({Yr:32},t),t=new T4(l,m,p,"_"+U4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(v=g.x2("<html>"+n+"</html>"),v.getElementsByTagName("parsererror").length?
(x=v.createElement("span"),x.appendChild(v.createTextNode(n))):x=v.firstChild,Unb(this,p,m-(p-l),h,t,0<r,x,e,c)):p=Vnb(n)+f}xob.lastIndex=0}}return c};
var wob=/^NOTE/,vob=/(?:\r\n|\r|\n){2,}/,xob=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yob=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.BY.oI(j5,{B:"wvppt"});g.w(k5,g.I);k5.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
k5.prototype.reset=function(){this.j&&this.j.reset()};
k5.prototype.xa=function(){g.I.prototype.xa.call(this);this.clear()};var t5={windowColor:"#080808",windowOpacity:0,textAlign:2,Ol:7,Zj:50,ao:100,isDefault:!0,Ue:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.w(l5,g.$V);g.k=l5.prototype;g.k.xa=function(){if(this.D||this.Ea){var a=this.J.mf();a&&!a.isDisposed()&&a.By()}else sob(this,!1);g.$V.prototype.xa.call(this)};
g.k.tR=function(){return this.X.L("html5_honor_caption_availabilities_in_audio_track")&&!this.bb};
g.k.Pt=function(){if(this.Xa)return this.D||this.Ea;var a=this.getAudioTrack();if(this.tR()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Qmb(a,g.JS(this.X));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?m5(this):hob(this)||m5(this)?!0:iob(this)};
g.k.load=function(){var a=this;g.$V.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.Za.clear(),this.D?mob(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.kt(this.B,"json3",function(b,c,d,e){if(b){var f;nob(a,null!=(f=a.B)?f:void 0);a.j.xQ()&&(a.Fa=[],a.J.yf("captions"),g.Su(a.La),a.Za.reset());if(a.videoData.Jm){var h;d=(null!=(h=d)?h:0)+a.videoData.Jm}b=bob(a.Za,b,c,d,e);if(a.ib)for(c=g.u(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.nm=a.videoData.Jm;c=!a.X.L("html5_keep_caption_data_after_seek")&&a.bb;a.player.sf(b,void 0,c);!a.W||a.Ea||p5(a)||g.eK(a.X)||g.AS(a.X)||g.GH(a.X)||"shortspage"===a.X.La||a.player.isInline()||(g.Wu(a.Na),b=Knb({Ol:0,Zj:5,ao:5,qr:2,textAlign:0,Ki:0,lang:"en-GB"}),a.Ta=[b],c=["Click "," for settings"],a.qb||(e=new g.DG(g.Zva()),g.M(a,e),a.qb=e.element),e=b.end-b.start,(f=g.YS(a.B))&&a.Ta.push(new R4(b.start,e,0,b.id,f)),a.Ta.push(new R4(b.start,e,0,b.id,c[0]),new R4(b.start,e,0,b.id,a.qb,!0),new R4(b.start,
e,0,b.id,c[1],!0)),a.player.sf(a.Ta),g.Uu(a.Na));!a.W||a.Ea||p5(a)||(g.JS(a.X)?r5(a,!0):s5(a,!0),a.N&&(a.N.D=a.B),a.player.uo());a.W=!1}}),this.D||this.Ea||p5(this)||this.player.wc("captionschanged",g.ZS(this.B))):(this.j=job(this),g.M(this,this.j),this.j.Lz(function(){lob(a)}))};
g.k.unload=function(){this.D&&this.B?mob(this,!1):(this.Na&&g.Wu(this.Na),this.player.yf("captions"),this.Fa=[],this.j&&this.j.Gr(),this.Za.clear(),this.Z&&this.player.sf(this.Z),this.WR());g.$V.prototype.unload.call(this);this.player.uo();this.player.wc("captionschanged",{})};
g.k.create=function(){this.Pt()&&this.load();var a;a:{var b,c,d;if(this.X.L("suggest_caption_correction_menu_item")&&this.X.L("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.u(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.oa("showpromotooltip",this.K.element)};
g.k.X$=function(){for(var a=this.J.mf().Jb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=g.aW(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&q5(this,b,!0)};
g.k.vca=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);g.Su(this.La)};
g.k.onCueRangeExit=function(a){g.Ib(this.Fa,a);this.j instanceof H4&&this.j.K&&this.player.Xn([a]);g.Su(this.La)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.Yaa=function(){rob(this,this.Ta);this.Ta=null};
g.k.UR=function(){var a=this;if(!this.zb||!this.D){this.La.stop();g.eba(this.Ua);this.Fa.sort(g.iAa);var b=this.Fa;if(this.Z){var c=g.rt(b,function(f){return-1===this.Z.indexOf(f)},this);
c.length&&(b=c)}b=g.u(b);for(c=b.next();!c.done;c=b.next())pob(this,c.value);b=g.u(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={rz:void 0,Vo:void 0},d=b.next()){var e=g.u(d.value);d=e.next().value;e=e.next().value;c.rz=d;c.Vo=e;this.Ua[c.rz]?(c.Vo.element.parentNode||(c.Vo instanceof i5||c.Vo instanceof d5||g.ed(this.ra,function(f){return function(h,l){l!==f.rz&&h.B.params.Ol===f.Vo.B.params.Ol&&h.B.params.Zj===f.Vo.B.params.Zj&&h.B.params.ao===f.Vo.B.params.ao&&(h.dispose(),delete a.ra[l]);
return l===f.rz}}(c),this),this.K.element.appendChild(c.Vo.element)),c.Vo.cB(this.Ua[c.rz])):(c.Vo.dispose(),delete this.ra[c.rz])}}};
g.k.dba=function(){fob(this,{},!0);this.player.wc("captionssettingschanged")};
g.k.z6=function(){var a=t5.Ue;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:t5.windowColor,windowOpacity:t5.windowOpacity};var b=Xmb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.g0=function(a,b){var c={};Object.assign(c,Xmb());Object.assign(c,a);fob(this,c,b);this.player.wc("captionssettingschanged")};
g.k.WR=function(){!this.D&&this.loaded&&(g.bd(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.UR())};
g.k.Eh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.we(b,-2,4);this.g0({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&q5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.X.K&&(g.JS(this.X)?r5(this,!!b):s5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.cb(b))break;if(g.md(b)){q5(this,null,!0);break}a=g.aW(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Rmb(e,b.translationLanguage):e)}this.IK(b.position);!c||c===this.B&&this.loaded||(b=g.iMa(),a=g.$S(c),b.length&&a===b[b.length-1]||(b.push(a),g.oD("yt-player-caption-language-preferences",b)),g.JS(this.X)&&!this.J.isInline()&&g.oD("yt-player-caption-sticky-language",a,2592E3),q5(this,c,!0))}else return this.loaded&&this.B&&!p5(this)?g.ZS(this.B):{};return"";case "tracklist":return this.j?g.Fr(g.aW(this.j.B,!(!b||!b.includeAsr)),function(f){return g.ZS(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||sob(this,!!b);break;case "sampleSubtitlesCustomized":this.D||sob(this,!!b,b);break;case "recommendedTranslationLanguages":return g.iMa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.K&&a.push("stickyLoading");return a};
g.k.Bq=function(){var a=this.B;if(this.X.L("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.EB)?b:null)?{cc:g.MQa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.$S(a)),{cc:b}):{}};
g.k.hca=function(){this.isSubtitlesOn()?(g.JS(this.X)?r5(this,!1):s5(this,!1),nob(this),this.unload(),m5(this,!0)&&q5(this,n5(this),!1)):this.K_()};
g.k.K_=function(){this.isSubtitlesOn()||q5(this,p5(this)||!this.B?o5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!p5(this)};
g.k.N8=function(){var a=p5(this);m5(this,a)?q5(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.tR()&&(this.W=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Pt()&&(a?q5(this,o5(this),!1):this.load()))};
g.k.IK=function(a){a&&(this.ma={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ma.top+"%",this.K.element.style.left=100*this.ma.left+"%",this.K.element.style.width=100*this.ma.width+"%",this.K.element.style.height=100*this.ma.height+"%",this.K.element.style.position="absolute",a=qob(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){"newdata"===a&&(this.videoData=b,this.loaded&&this.unload(),this.W=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.wc("captionschanged",{})),this.Pt()&&this.load())};
g.k.getAudioTrack=function(){return this.ib&&2===this.player.getPresentingPlayerType()?this.videoData.jl:this.player.getAudioTrack()};
g.k.y9=function(){var a=this.J.mf();a&&!a.isDisposed()&&a.By();this.J.isFullscreen()?(this.D=this.Xa=!0,this.loaded&&lob(this)):(this.Xa="3"===this.X.controlsType,this.D=eob(this));q5(this,this.B)};
g.k.hL=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.jb("innertubeCommand",d)};
g.BY.oI(l5,{UR:"smucd"});g.ZV("captions",l5);})(_yt_player);
